version: "3"

volumes:
  nodejs-express-auth-service:
  postgres-data:

services:
  web:
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "npm run migration:run && node dist/index.js"

  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -p 5432 -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 5s
